language: python
python:
   - "3.6"
   - "3.7"

before_install:
   - sudo apt-get install python3-dev
   - sudo apt install build-essential python-dev libxml2 libxml2-dev zlib1g-dev
   - sudo add-apt-repository ppa:igraph/ppa -y
   - sudo rm -rf /var/lib/apt/lists/*
   - sudo rm -rf /etc/apt/sources.list.d/*
   - sudo apt-get update
   - sudo apt-get install python-igraph

install:
   - pip3 install -r requirements.txt
   - pip3 install pytest
   - pwd
   - pip3 install -e .
   - pip3 install codecov
   - pip install pytest-cov

script: 
   - pytest --cov=netZooPy tests

branches:
  only:
  - master
  - devel

after_success:
   - codecov
