language: python
python:
   - "3.6"
   - "3.7"

install:
   - pip3 install -r requirements.txt
   - pip3 install pytest
   - pwd
   - pip3 install -e .
   - pip3 install --user codecov

script: 
   - pytest

after_success:
   - codecov
