language: java

matrix:
  include:
  - os: osx
    before_install:
    - brew install python3
  - os: linux
    before_install:
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt-get update
    - sudo apt install software-properties-common
    - sudo apt-get install python3-pip
    - pip3 install --upgrade pip
    - sudo apt-get install python3-setuptools
    - sudo apt-get install python3.6
    - pyenv global 3.6
    - pip3.6 install -r requirements.txt
    - pip3.6 install pytest
    - pwd
    - pip3.6 install -e .
    - pip3.6 install codecov
    - pip3.6 install pytest-cov
    script: 
    - travis_wait python3.6 -m pytest --cov=netZooPy tests

branches:
  only:
  - master
  - devel

after_success:
   - codecov
